config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  post 'comments/create'
  get 'comments/destroy'
  get 'login', to: 'session#login'
  post 'session/create'
  get 'logout', to: 'session#logout'
  resources :posts
  resources :users
  root 'posts#index'
end

app/controllers/session_controller.rb
# frozen_string_literal: true

class SessionController < ApplicationController
  skip_before_action :require_login, only: %i[login create]

  def login; end

  def create
    user = User.find_by(username: params[:username])
    p user&.username

    if user&.authenticate(params[:password])
      p 'success'
      sign_in user
      redirect_to root_path
    else
      flash[:error] = t('forms.messages.invalid_credentials')
      redirect_to login_path
    end
  end

  def logout
    sign_out
    redirect_to login_path
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def sign_in(user)
    # cookies.signed[:user_id] = { value: user.id, expires: 10.days, http_only: true }
    session[:current_user_id] = user.id
    self.current_user = user
  end

  def signed_in?
    !session[:current_user_id].nil?
  end

  def sign_out
    # cookies.signed[:user_id] = nil
    session[:current_user_id] = nil
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:current_user_id])
    # cookies.signed[:user_id])
  end
end

app/views/session/login.html.erb
<% flash[:error]&.tap do |error| %>
    <div class="alert alert-danger"><%= error %></div>
<% end %>
<%= form_with url: session_create_url, method: :post, locale: true do |f|%>
    <%= f.label t('forms.username'), style: "display: block" %>
    <%= f.text_field :username, required: true %><br/>
    <%= f.label t('forms.password'), style: "display: block" %>
    <%= f.password_field :password, required: true %><br/>
    <%= f.submit t('forms.sign_in'), required: true %>
<% end %>

<%= link_to t('forms.registration'), {controller: :users, action: :new} %>