config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  post 'comments/create'
  get 'comments/destroy'
  get 'login', to: 'session#login'
  post 'session/create'
  get 'logout', to: 'session#logout'
  resources :posts
  resources :users
  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :comment, optional: true # root comment
  before_save :create_root_comment
  before_destroy :destroy_root_comment
  validates_presence_of :title, :body
  belongs_to :user

  def get_comments
    comment.subtree
  end

  private

  def create_root_comment
    self.comment = Comment.create(user: user, comment_id: nil, contents: 'root')
  end

  def destroy_root_comment
    comment.destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  # frozen_string_literal: true
  
  before_action :check_access, only: %i[edit update destroy]
  skip_before_action :require_login, only: %i[index show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def check_access
    refuse_with_method_not_allowed unless @post.user == current_user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
    <b><%= t 'forms.errors', count: user.errors.count %></b>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label t('forms.title'), style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label t('forms.body'), style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit t('forms.create_post')%>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong><%= t('forms.username') %>:</strong>
    <%= post.user.username %>
  </p>

  <p>
    <strong><%= t('forms.title') %>:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong><%= t('forms.body') %>:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1><%= t('forms.editing_post') %></h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to t('forms.show_this_post'), @post %> |
  <%= link_to t('forms.back_to_posts'), posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t('forms.posts') %></h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to t('forms.show_this_post'), post %>
    </p>
  <% end %>
</div>

<%= link_to t('forms.new_post'), new_post_path %>

app/views/posts/new.html.erb
<h1><%= t('forms.new_post') %></h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to t('forms.back_to_posts'), posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<h2><%= t('forms.comments') %>:</h2>
<% @post.get_comments.each do |entry| %>
  <div style="margin-left: <%= (entry[:level] - 1) * 50 %>px">
    <strong><%= entry[:comment].user.username %></strong>:
    <%= entry[:comment].contents %>
    <%= link_to t('forms.respond'), comments_new_path(comment: entry[:comment], post: @post) %>
    <% if entry[:comment].user == @current_user %>
      <%= link_to t('forms.delete'), comments_destroy_path(comment: entry[:comment], post: @post) %>
    <% end %>
  </div>
<% end %>

<%= link_to t('forms.comment'), comments_new_path(comment: @post.comment, post: @post) %>



<div>
  <%= link_to t('forms.edit_this_post'), edit_post_path(@post) %> |
  <%= link_to t('forms.back_to_posts'), posts_path %>
  <%= button_to t('forms.destroy_this_post'), @post, method: :delete %>
</div>